---
- name: Download kind binary
  ansible.builtin.get_url:
    url: https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: '0700'

- name: Add k9s
  ansible.builtin.package:
    name: k9s
    state: present
