---
- name: Download kind binary
  ansible.builtin.get_url:
    url: https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: '0700'

- name: Add k9s
  ansible.builtin.dnf:
    name: 'https://github.com/derailed/k9s/releases/download/v0.30.8/k9s_linux_amd64.rpm'
    disable_gpg_check: true
    state: present
