---
- name: Enable copr lazzygit repo
  ansible.builtin.shell: dnf copr enable atim/lazygit -y

- name: Ensure basic packages
  ansible.builtin.package:
    name: 
      - nitrogen
      - NetworkManager-tui
      - python3-netifaces
      - python3-libvirt
      - rofi
      - ripgrep
      - rust
      - cargo
      - fd-find
      - nodejs
      - golang
      - lazygit
    state: present

- name: Add bubblebee
  become: false
  ansible.builtin.pip:
    name: bumblebee-status
    extra_args: "--user"
    state: present

- name: Ensure bubblebee dependencies
  ansible.builtin.pip:
    name: 
     - psutil
    state: present

- name: Ensure i3wm config
  ansible.builtin.template:
    src: templates/i3wm.j2
    dest: "/home/{{ username }}/.config/i3/config"

- name: Ensure rofi theme tokyonight
  ansible.builtin.template:
    src: templates/rofi-tokyonight.rasi.j2
    dest: "/usr/share/rofi/themes/tokyonight.rasi"

- name: Ensure rofi config
  ansible.builtin.template:
    src: templates/roficonfig.rasi.j2
    dest: "/home/{{ username }}/.config/rofi/config.rasi"
