---
- name: Ensure basic packages
  ansible.builtin.package:
    name: 
      - nitrogen
      - NetworkManager-tui
      - python3-netifaces
      - python3-libvirt
    state: present

- name: Add bubblebee
  ansible.builtin.pip:
    name: bumblebee-status
    args: --user
    status: present

- name: Ensure bubblebee dependencies
  ansible.builtin.pip:
    name: 
     - psutil
    status: present

- name: Ensure i3wm config
  ansible.builtin.template:
    src: templates/i3wm.j2
    dest: ~/.config/i3/config
