---
- name: Ensure basic packages
  ansible.builtin.package:
    name: 
      - nitrogen
      - NetworkManager-tui
      - python3-netifaces
      - python3-libvirt
    state: present

- name: Add bubblebee
  become_user: "{{ username }}"
  ansible.builtin.pip:
    name: bumblebee-status
    extra-args: "--user"
    state: present

- name: Ensure bubblebee dependencies
  ansible.builtin.pip:
    name: 
     - psutil
    state: present

- name: Ensure i3wm config
  ansible.builtin.template:
    src: templates/i3wm.j2
    dest: "/home/{{ username }}/.config/i3/config"
