---
- name: Add basic packages package
  ansible.builtin.package:
    name:
      - nmtui
      - zsh
    state: present

- name: Install vagrant and libvirt
  ansible.builtin.include_tasks:
    file: vagrant.yaml

- name: Install docker
  ansible.builtin.include_tasks:
    file: docker.yaml

- name: Install kind k8s
  ansible.builtin.include_tasks:
    file: kind.yaml

- name: Install k9s cli
  ansible.builtin.include_tasks:
    file: k9s.yaml
