---
- name: Add basic packages package
  ansible.builtin.package:
    name:
      - nmtui
      - zsh
    state: present

- name: Download ohmyzsh instaler
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh

- name: Execute ohmyzsh zsh-installer
  ansible.builtin.shell: /tmp/zsh-installer.sh

- name: Configure ohmyzsh
  ansible.builtin.template:
    src: templates/ohmyzsh.j2
    dest: ~/.zshrc

- name: Configure bashrc
  ansible.builtin.template:
    src: templates/bashrc.j2
    dest: ~/.bashrc

- name: Install vagrant and libvirt
  ansible.builtin.include_tasks:
    file: vagrant.yaml

- name: Install docker
  ansible.builtin.include_tasks:
    file: docker.yaml

- name: Install kind k8s
  ansible.builtin.include_tasks:
    file: kind.yaml

- name: Install k9s cli
  ansible.builtin.include_tasks:
    file: k9s.yaml
