---
- name: Add basic packages package
  ansible.builtin.package:
    name:
      - nmtui
      - kitty
    state: present

- name: Add kitty tokio night theme
  ansible.builtin.template:
    src: templates/kitty.conf.j2
    dest: ~/.config/kitty/kitty.conf
