---
- name: Add neovim
  ansible.builtin.package:
    name: neovim
    state: present

- name: Download lazzyvim config
  ansible.builtin.git:
    repo: 'https://github.com/apecnascimento/nvim-config.git'
    dest: '/home/{{ username }}/.config/nvim'
